# Generated by Django 5.0.2 on 2024-03-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_status_orders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='request_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
