# Generated by Django 5.0.2 on 2024-03-17 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_items_item_name_alter_items_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item_id',
            new_name='item_name',
        ),
    ]
