# Generated by Django 5.0.2 on 2024-03-17 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_rename_item_name_orders_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEntity',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('order_status', models.CharField(default='New', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RequestRow',
            fields=[
                ('request_row_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(choices=[('0', 'UNIT0'), ('1', 'UNIT1'), ('2', 'UNIT2')], default='0', max_length=50)),
                ('quantity', models.IntegerField()),
                ('price_without_vat', models.FloatField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.items')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.requestentity')),
            ],
        ),
    ]
