# Generated by Django 5.0.2 on 2024-03-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_requestrow_request_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='list_of_orders',
        ),
        migrations.AddField(
            model_name='order',
            name='list_of_orders',
            field=models.ManyToManyField(related_name='list_of_orders', to='warehouse.orderitem'),
        ),
    ]
