# Generated by Django 5.0.2 on 2024-03-17 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_remove_order_list_of_orders_order_list_of_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='list_of_orders',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='warehouse.order'),
        ),
    ]
