# Generated by Django 5.0.2 on 2024-03-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
