# Generated by Django 5.0.2 on 2024-03-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_orderitem_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(default='None', max_length=50, unique=True),
        ),
    ]
